package service;

import java.lang.reflect.Method;

import exception.RemoteException;
import message.ExceptionMessage;
import message.MethodInvocationMessage;
import message.ReturnMessage;
import server.Remote;
import server.RemoteRef;
import server.RemoteStub;
import shareFolder.Hello_Interface;
import util.CommunicationUtil;
import util.Util;
/**
 * This is automatic generated by RMIC.
 *
 */
public class Hello_Interface_Impl_Stub implements RemoteStub, Remote, Hello_Interface {
	RemoteRef ref;
	
	public Hello_Interface_Impl_Stub(RemoteRef r) {
		this.ref = r;
	}
	
	@Override
	public RemoteRef getRR() {
		return ref;
	}
	
	@Override
	public String sayHello(String name) {
		Class<?>[] types = new Class<?>[1];
		types[0] = String.class;
		Method method;
		try {
			method = this.getClass().getMethod("sayHello", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[1];
		params[0] = name;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		
		return (String)((ReturnMessage)obj).get();
	}

	@Override
	public String sayHello(String name, Long meters) {
		Class<?>[] types = new Class<?>[2];
		types[0] = String.class;
		types[1] = Long.class;
		Method method;
		try {
			method = this.getClass().getMethod("sayHello", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[2];
		params[0] = name;
		params[1] = meters;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return (e.getType().toString() + ": "+ e.getCause().toString());
		}
		
		return (String)((ReturnMessage)obj).get();
	}

}
