package service;

import java.io.Serializable;
import java.lang.reflect.Method;

import message.ExceptionMessage;
import message.MethodInvocationMessage;
import message.ReturnMessage;
import exception.RemoteException;
import server.Remote;
import server.RemoteRef;
import server.RemoteStub;
import shareFolder.NameServer;
import util.CommunicationUtil;
import util.Util;
/**
 * This is automatic generated by RMIC.
 *
 */
public class NameServerImpl_Stub implements NameServer, Remote, RemoteStub, Serializable {
	private static final long serialVersionUID = -2376458860726302386L;
	RemoteRef ref;
	
	public NameServerImpl_Stub(RemoteRef ref) {
		this.ref = ref;
	}
	
	@Override
	public RemoteRef getRR() {
		return this.ref;
	}

	@Override
	public RemoteRef match(String name) {
		Class<?>[] types = new Class<?>[1];
		types[0] = String.class;
		Method method;
		try {
			method = this.getClass().getMethod("match", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[1];
		params[0] = name;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		return (RemoteRef) ((ReturnMessage) obj).get();
	}

	@Override
	public NameServer add(String s, RemoteRef r, NameServer n) {
		Class<?>[] types = new Class<?>[3];
		types[0] = String.class;
		types[1] = RemoteRef.class;
		types[2] = NameServer.class;
		Method method;
		try {
			method = this.getClass().getMethod("add", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[3];
		params[0] = s;
		params[1] = r;
		params[2] = n;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		return (NameServer) ((ReturnMessage) obj).get();
	}

	@Override
	public NameServer next() {
		Class<?>[] types = new Class<?>[0];
		Method method;
		try {
			method = this.getClass().getMethod("next", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[0];
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		return (NameServer) ((ReturnMessage) obj).get();
	}
	
	
}
