package service;

import java.lang.reflect.Method;

import message.ExceptionMessage;
import message.MethodInvocationMessage;
import message.ReturnMessage;
import exception.RemoteException;
import server.Remote;
import server.RemoteRef;
import server.RemoteStub;
import shareFolder.ZipCodeRList;
import util.CommunicationUtil;
import util.Util;
/**
 * This is automatic generated by RMIC.
 *
 */
public class ZipCodeRListImpl_Stub implements RemoteStub, Remote, ZipCodeRList {
	private static final long serialVersionUID = -5004044961058557033L;
	RemoteRef ref;
	
	public ZipCodeRListImpl_Stub(RemoteRef r) {
		this.ref = r;
	}
	
	@Override
	public String find(String city) {
		Class<?>[] types = new Class<?>[1];
		types[0] = String.class;
		Method method;
		try {
			method = this.getClass().getMethod("find", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return "";
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[1];
		params[0] = city;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return "";
		}
		return (String) ((ReturnMessage) obj).get();
	}

	@Override
	public ZipCodeRList add(String city, String zipcode) {
		Class<?>[] types = new Class<?>[2];
		types[0] = String.class;
		types[1] = String.class;
		Method method;
		try {
			method = this.getClass().getMethod("add", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[2];
		params[0] = city;
		params[1] = zipcode;
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		return (ZipCodeRList) ((ReturnMessage) obj).get();
	}

	@Override
	public ZipCodeRList next() {
		Class<?>[] types = new Class<?>[0];
		Method method;
		try {
			method = this.getClass().getMethod("next", types);
		} catch (NoSuchMethodException | SecurityException e) {
			System.out.println("No such method!");
			return null;
		}
		int key = (int) Util.computeMethodHash(method);
		Object[] params = new Object[0];
		MethodInvocationMessage message = new MethodInvocationMessage(ref.getInstanceID(), key, params);
		Object obj = null;
		
		try {
			try {
				CommunicationUtil.sendMessage(ref.getHost(), ref.getPort(), message);
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			try {
				obj = CommunicationUtil.receiveMessage(ref.getHost(), ref.getPort());
			} catch (exception.RemoteException e) {
				System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
				e.printStackTrace();
			}
			if(obj instanceof ExceptionMessage)
				throw (RemoteException)((ExceptionMessage)obj).get();
		} catch (RemoteException e) {
			System.err.println(e.getType().toString() + ": "+ e.getCause().toString());
			return null;
		}
		return (ZipCodeRList) ((ReturnMessage) obj).get();
	}

	@Override
	public RemoteRef getRR() {
		return ref;
	}
}
